# This file may be used to create an environment using:
# $ conda env create -f <this file>
name: snakemake_assemble
channels:
  - conda-forge
  - defaults
  - biocore
  - r
  - anaconda
  - bioconda
dependencies:
  - graphviz=2.38.0
  - python=3
  - snakemake
  - pyyaml
  - fastqc
  - multiqc
  - skewer
  - bowtie2
  - bedtools
  - samtools
  - cramtools
  - megahit
  - spades
  - maxbin2
  - bbmap
  - prodigal
  - biopython
  - pandas
